name: Release
on:
  workflow_dispatch: { }
#  push:
#    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    # Don't trigger releases on release commits. We need this because
    # releases create new commits, and we don't want to re-release
    # based on these new commits.
    if: "!startsWith(github.ref, 'refs/tags/v')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release